### ISSUE TITLE
Need an interface to add an additional field to the request

### ISSUE THREAD

**Issue by styx** [gokerDEV/droparea#10]
In Rails it is very important as protection against of XSRF attacks is used. It means that for `GET` and `POST` methods a special token must be send -> requires to turn off protection as your plugin doesn't support adding of custom fields to the request (or patch a plugin).

Thanks for development.

**Comment by styx** [comment]
Here is the patch I'm currently using for Rails 3.x

```
 (function( $ ){
+
+  function authToken() {
+    return $('meta[name="csrf-token"]').attr('content');
+  };
+
   var s;
   // Methods
   var m = {
@@ -193,6 +198,8 @@
           fd.append(i, input.data(i));
       // Add file data
       fd.append(input.attr('name'), file);
+      // Add Rails auth token
+      fd.append('authenticity_token', authToken());
       // Send data
       xhr.send(fd);
     },
```

**Comment by shybovycha** [comment]
Created a pull request that fixes this already. It does not add an interface as you requested (saw your comment just now), but it fixes Devise anyway. https://github.com/gokercebeci/droparea/pull/12
