### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by aleray** [gokerDEV/droparea#5]
Hello,

I'm considering using your plugin as a starting point for a work of mine. Could you tell me under what license is your source code released?

All the best,

Alex

**Comment by gokerDEV** [comment]
Hi Alex,

I'm working on a new version now. I have not decided about licence
issues. It will probably be "MIT".
If only you could wait for a couple days until the release of the new
version, it will be decided then

Regards

goker.cebeci

2011/5/10 aleray <
reply@reply.github.com>

**Comment by gokerDEV** [comment]
Hi Alex,

It's done.

**Comment by aleray** [comment]
Thanks, it's really nice.

;-)
